### ISSUE TITLE
WIP asset loading fails after fresh install

### ISSUE THREAD

**Issue by juhat** [AppMaintainers/beloved-projects#126]
I am not sure about this one as this happened in other projects too in the past. 

When I seed the db, start the server, start the webpacker server, I got no assets served. I tried with bin/webpacker-dev-server and also with bin/webpacker -w, none of them worked. 

![Screenshot 2024-04-24 at 10 05 48](https://github.com/AppMaintainers/beloved-projects/assets/40239/ee3c327b-5dcd-431c-89f6-1769dc56b954)

Does anyone experienced the same issue?

**Comment by Gregurevic** [comment]
Closing as per agreed.
