### ISSUE TITLE
forms and feedbacks

### ISSUE THREAD

**Issue by Gregurevic** [AppMaintainers/beloved-projects#180]
Ennek az issuenak a lefejlesztése után: (use-case-ek)
- "konzol hozzáféréssel rendelkező aktor" tud konzolból form-ot létrehozni
- a form tulajdonságait ismerve, a "konzol hozzáféréssel rendelkező aktor" tud formhoz kapcsolódó linket készíteni
- ennek a linknek a birtokában lévő, de nem authorizált aktor tud form-ot látni és tölteni

[A felépítendő modell struktúra UML diagrammja itt található.](https://drive.google.com/file/d/1vBfkAEF-z-y9d_I9W7LOsE8WoxjQcll-/view?usp=sharing)

A feléptendő kontroller struktúra és nézetek:
- `forms#show` (ahol a kész form kitölthető)
- `feedbacks#create` (ahova a kitöltött form beküldhető)
- `static_pages#feedback_given` (ahova a sikeres kitöltés után átirányítjuk a felhasználót. csak egy "thanks for filling out" üzenet van az oldalon)
Fontos, hogy ezek a nézetek mind elérhetők nem authorizált, de a megfelelő linkek birtokában lévő felhasználóknak.

Az issue része a tesztelés is:
- a megfelelő Faker osztályok létrehozása
- controller akciók (megfelelő linkkel és a nélkül)
- policy-k (megoldás függően)
- (megoldás függően) a Form "secret" előállításának a tesztelése

**Comment by ebence** [comment]
Köszi Gergő, király!
